// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/video.proto

package video

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetVideosRequest struct {
	Query                string   `protobuf:"bytes,1,opt,name=query" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVideosRequest) Reset()         { *m = GetVideosRequest{} }
func (m *GetVideosRequest) String() string { return proto.CompactTextString(m) }
func (*GetVideosRequest) ProtoMessage()    {}
func (*GetVideosRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_video_4ef3b5c535febc68, []int{0}
}
func (m *GetVideosRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVideosRequest.Unmarshal(m, b)
}
func (m *GetVideosRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVideosRequest.Marshal(b, m, deterministic)
}
func (dst *GetVideosRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVideosRequest.Merge(dst, src)
}
func (m *GetVideosRequest) XXX_Size() int {
	return xxx_messageInfo_GetVideosRequest.Size(m)
}
func (m *GetVideosRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVideosRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetVideosRequest proto.InternalMessageInfo

func (m *GetVideosRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type GetVideosResponse struct {
	Query                string   `protobuf:"bytes,1,opt,name=query" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVideosResponse) Reset()         { *m = GetVideosResponse{} }
func (m *GetVideosResponse) String() string { return proto.CompactTextString(m) }
func (*GetVideosResponse) ProtoMessage()    {}
func (*GetVideosResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_video_4ef3b5c535febc68, []int{1}
}
func (m *GetVideosResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVideosResponse.Unmarshal(m, b)
}
func (m *GetVideosResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVideosResponse.Marshal(b, m, deterministic)
}
func (dst *GetVideosResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVideosResponse.Merge(dst, src)
}
func (m *GetVideosResponse) XXX_Size() int {
	return xxx_messageInfo_GetVideosResponse.Size(m)
}
func (m *GetVideosResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVideosResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetVideosResponse proto.InternalMessageInfo

func (m *GetVideosResponse) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func init() {
	proto.RegisterType((*GetVideosRequest)(nil), "video.GetVideosRequest")
	proto.RegisterType((*GetVideosResponse)(nil), "video.GetVideosResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for VideoService service

type VideoServiceClient interface {
	Echo(ctx context.Context, in *GetVideosRequest, opts ...grpc.CallOption) (*GetVideosResponse, error)
}

type videoServiceClient struct {
	cc *grpc.ClientConn
}

func NewVideoServiceClient(cc *grpc.ClientConn) VideoServiceClient {
	return &videoServiceClient{cc}
}

func (c *videoServiceClient) Echo(ctx context.Context, in *GetVideosRequest, opts ...grpc.CallOption) (*GetVideosResponse, error) {
	out := new(GetVideosResponse)
	err := grpc.Invoke(ctx, "/video.VideoService/Echo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for VideoService service

type VideoServiceServer interface {
	Echo(context.Context, *GetVideosRequest) (*GetVideosResponse, error)
}

func RegisterVideoServiceServer(s *grpc.Server, srv VideoServiceServer) {
	s.RegisterService(&_VideoService_serviceDesc, srv)
}

func _VideoService_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVideosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/video.VideoService/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).Echo(ctx, req.(*GetVideosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VideoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "video.VideoService",
	HandlerType: (*VideoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _VideoService_Echo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/video.proto",
}

func init() { proto.RegisterFile("proto/video.proto", fileDescriptor_video_4ef3b5c535febc68) }

var fileDescriptor_video_4ef3b5c535febc68 = []byte{
	// 179 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0xcb, 0x4c, 0x49, 0xcd, 0xd7, 0x03, 0xb3, 0x85, 0x58, 0xc1, 0x1c, 0x29, 0x99,
	0xf4, 0xfc, 0xfc, 0xf4, 0x9c, 0x54, 0xfd, 0xc4, 0x82, 0x4c, 0xfd, 0xc4, 0xbc, 0xbc, 0xfc, 0x92,
	0xc4, 0x92, 0xcc, 0xfc, 0xbc, 0x62, 0x88, 0x22, 0x25, 0x0d, 0x2e, 0x01, 0xf7, 0xd4, 0x92, 0x30,
	0x90, 0xca, 0xe2, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x11, 0x2e, 0xd6, 0xc2, 0xd2,
	0xd4, 0xa2, 0x4a, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x08, 0x47, 0x49, 0x93, 0x4b, 0x10,
	0x49, 0x65, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0x2a, 0x76, 0xa5, 0x46, 0x09, 0x5c, 0x3c, 0x60, 0x75,
	0xc1, 0xa9, 0x45, 0x65, 0x99, 0xc9, 0xa9, 0x42, 0x01, 0x5c, 0x2c, 0xae, 0xc9, 0x19, 0xf9, 0x42,
	0xe2, 0x7a, 0x10, 0xf7, 0xa1, 0xdb, 0x28, 0x25, 0x81, 0x29, 0x01, 0xb1, 0x40, 0x49, 0xb4, 0xe9,
	0xf2, 0x93, 0xc9, 0x4c, 0xfc, 0x4a, 0x5c, 0xfa, 0x65, 0x86, 0x10, 0xdf, 0x15, 0x5b, 0x31, 0x6a,
	0x25, 0xb1, 0x81, 0x5d, 0x6f, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xc1, 0x98, 0x3d, 0x4c, 0xf7,
	0x00, 0x00, 0x00,
}
